//! `nessemble` command-line interface.
//!
//! Argument parsing is handled by [`clap`] (derive): the top-level struct
//! carries the assemble-mode flags plus an optional subcommand
//! (`init`/`scripts`/`reference`/`lsp`/`format`). Help and usage text are
//! generated by clap from the field/attribute metadata rather than
//! hand-maintained. The out-of-scope options (`-d`/`-R`/`-s`/`-r`) and commands
//! (registry/package/user) are omitted entirely — they are not declared and so
//! appear nowhere in help.
//!
//! `-v`/`--version` and `-L`/`--license` keep their reference banners (version
//! header, copyright line, GPL notice) rather than clap's one-line version, so
//! that branded output is preserved; clap's own version flag is disabled in
//! favor of these.

mod custom;
mod format;
mod home;
mod init;
mod lsp;
mod rc;
mod reference;
mod scripts;
mod usage;

use std::io::{Read, Write};
use std::path::PathBuf;
use std::process::ExitCode;

use clap::{Parser, Subcommand};
use nessemble_core::{
    assemble_file_with, assemble_with, render_coverage, render_list_file, AssembleError, Options,
};
use nessemble_i18n::t;

/// Return codes mirroring the reference tool.
const RETURN_OK: u8 = 0;
const RETURN_EPERM: u8 = 1;
const RETURN_USAGE: u8 = 129;

/// The `nessemble` assembler.
///
/// With no subcommand, assembles the input file (or stdin) into a ROM.
#[derive(Parser)]
#[command(
    name = "nessemble",
    // `-v`/`--version` and `-L`/`--license` are provided below with their
    // reference banners; suppress clap's built-in one-line `--version`.
    disable_version_flag = true,
    // The assemble-mode positional (`<infile.asm>`) coexists with the
    // subcommands; a leading token matching a subcommand name selects it.
    args_conflicts_with_subcommands = true,
    subcommand_negates_reqs = true
)]
struct Cli {
    /// output file
    #[arg(short = 'o', long, value_name = "outfile.rom")]
    output: Option<String>,

    /// output format
    #[arg(short = 'f', long, value_name = "NES|RAW")]
    format: Option<String>,

    /// empty byte value
    #[arg(short = 'e', long, value_name = "hex")]
    empty: Option<String>,

    /// use undocumented opcodes
    #[arg(short = 'u', long)]
    undocumented: bool,

    /// generate list of labels and constants
    #[arg(short = 'l', long, value_name = "listfile.txt")]
    list: Option<String>,

    /// use custom pseudo-instruction functions
    #[arg(short = 'p', long, value_name = "pseudo.txt")]
    pseudo: Option<String>,

    /// check syntax only
    #[arg(short = 'c', long)]
    check: bool,

    /// log data coverage
    #[arg(short = 'C', long)]
    coverage: bool,

    /// display program version
    #[arg(short = 'v', long)]
    version: bool,

    /// display program license
    #[arg(short = 'L', long)]
    license: bool,

    /// assembly source to assemble (stdin if omitted)
    #[arg(value_name = "infile.asm")]
    infile: Option<String>,

    #[command(subcommand)]
    command: Option<Command>,
}

/// The in-scope subcommands.
#[derive(Subcommand)]
enum Command {
    /// initialize new project
    Init {
        /// project values (filename, PRG banks, CHR banks, mapper, mirroring);
        /// any omitted are prompted for interactively
        #[arg(
            value_name = "arg",
            trailing_var_arg = true,
            allow_hyphen_values = true
        )]
        args: Vec<String>,
    },
    /// install scripts
    Scripts,
    /// get reference info about assembly terms
    Reference {
        /// category (`instructions` or `directives`)
        category: Option<String>,
        /// term within the category
        term: Option<String>,
    },
    /// run the language server (stdio)
    Lsp,
    /// format assembly source
    Format(format::FormatArgs),
}

fn main() -> ExitCode {
    // Load any translator-provided locales (`~/.nessemble/locales/<lang>.ftl`)
    // so `NESSEMBLE_LANG` can select them, falling back to the embedded en-US.
    if let Some(dir) = home::config_dir() {
        nessemble_i18n::load_locale_dir(&dir.join("locales"));
    }

    let cli = match Cli::try_parse() {
        Ok(cli) => cli,
        Err(e) => {
            // clap routes help/version to stdout and errors to stderr. We keep
            // the reference's single usage return code (129) for every early
            // exit — help display included — rather than clap's 0/2.
            let _ = e.print();
            return ExitCode::from(RETURN_USAGE);
        }
    };

    ExitCode::from(dispatch(cli))
}

/// Dispatch a parsed command line: `-v`/`-L`, a subcommand, or assemble mode.
fn dispatch(cli: Cli) -> u8 {
    if cli.version {
        print!("{}", usage::version());
        return RETURN_USAGE;
    }
    if cli.license {
        print!("{}", usage::license());
        return RETURN_USAGE;
    }

    match cli.command {
        Some(Command::Init { args }) => init::run(&args),
        Some(Command::Scripts) => scripts::run(),
        Some(Command::Lsp) => lsp::run(),
        Some(Command::Reference { category, term }) => {
            let (out, code) = reference::run(category.as_deref(), term.as_deref());
            print!("{out}");
            code
        }
        Some(Command::Format(args)) => format::run(&args),
        None => assemble_mode(&cli),
    }
}

/// Assemble the input (a positional file, or stdin) into the output.
fn assemble_mode(cli: &Cli) -> u8 {
    let mut options = Options {
        nes: matches!(cli.format.as_deref(), Some(f) if f.eq_ignore_ascii_case("nes")),
        undocumented: cli.undocumented,
        ..Options::default()
    };

    if let Some(empty) = cli.empty.as_deref() {
        options.empty_byte = parse_hex_byte(empty);
    }

    let input: Option<PathBuf> = cli.infile.as_deref().map(PathBuf::from);
    let result = match &input {
        Some(path) => assemble_file_with(
            path,
            &options,
            custom::build_resolver(cli.pseudo.as_deref()),
        ),
        None => match read_stdin() {
            Ok(source) => assemble_with(
                &source,
                &options,
                custom::build_resolver(cli.pseudo.as_deref()),
            ),
            Err(e) => {
                eprintln!("nessemble: could not read input: {e}");
                return RETURN_EPERM;
            }
        },
    };

    match result {
        Ok(assembly) => {
            for w in &assembly.warnings {
                eprintln!(
                    "{}",
                    t!(
                        "warning-line",
                        file = w.file,
                        line = w.line,
                        message = w.message
                    )
                );
            }
            if cli.check {
                println!("{}", t!("no-errors"));
                return RETURN_OK;
            }
            let output = cli.output.as_deref().unwrap_or("-");
            if let Err(e) = write_output(output, &assembly.rom) {
                eprintln!("nessemble: could not write output: {e}");
                return RETURN_EPERM;
            }
            if let Some(list) = cli.list.as_deref() {
                if let Err(e) = std::fs::write(list, render_list_file(&assembly.symbols)) {
                    eprintln!("nessemble: could not write list file: {e}");
                    return RETURN_EPERM;
                }
            }
            // Coverage is reported only for an iNES ROM written to a file,
            // matching the reference guard.
            if cli.coverage && output != "-" {
                if let Some(report) = &assembly.coverage {
                    print!("{}", render_coverage(report));
                }
            }
            RETURN_OK
        }
        Err(AssembleError(d)) => {
            eprintln!(
                "{}",
                t!(
                    "error-line",
                    file = d.file,
                    line = d.line,
                    message = d.message
                )
            );
            RETURN_EPERM
        }
    }
}

/// Parse a hex byte for `-e`, matching the reference `hex2int` (invalid → 0).
fn parse_hex_byte(s: &str) -> u8 {
    let trimmed = s.trim_start_matches("0x").trim_start_matches("0X");
    u8::from_str_radix(trimmed, 16).unwrap_or(0)
}

fn read_stdin() -> std::io::Result<String> {
    let mut buf = String::new();
    std::io::stdin().read_to_string(&mut buf)?;
    Ok(buf)
}

fn write_output(output: &str, bytes: &[u8]) -> std::io::Result<()> {
    if output == "-" {
        std::io::stdout().write_all(bytes)
    } else {
        std::fs::write(output, bytes)
    }
}
