//! Version and license output.
//!
//! The `-h`/`--help` usage text is now generated by clap (see [`crate`]); only
//! the `-v`/`--version` and `-L`/`--license` banners — the version header,
//! copyright line, and GPL notice — are rendered here, preserving the reference
//! tool's branded output.

use nessemble_i18n::t;

const PROGRAM_NAME: &str = "nessemble";
/// The displayed version is the workspace (crate) version — the single source
/// of truth that also drives the release pipeline.
const PROGRAM_VERSION: &str = env!("CARGO_PKG_VERSION");
const PROGRAM_COPYRIGHT: &str = "2017-2026";

/// The author name shown in the banner, taken from the workspace `authors`
/// metadata (`CARGO_PKG_AUTHORS`) so it lives in one place — the root
/// `Cargo.toml`. The first author is used, with any ` <email>` suffix stripped.
fn program_author() -> &'static str {
    let first = env!("CARGO_PKG_AUTHORS").split(':').next().unwrap_or("");
    first
        .split_once(" <")
        .map_or(first, |(name, _)| name)
        .trim()
}

/// The GPL notice printed by `--license` (the body after the version header).
const LICENSE_TEXT: &str = include_str!("../../../LICENSE.txt");

/// The version banner (`nessemble v<version>` + copyright line).
pub fn version() -> String {
    format!(
        "{PROGRAM_NAME} v{PROGRAM_VERSION}\n\n{} {PROGRAM_COPYRIGHT} {}\n",
        t!("label-copyright"),
        program_author()
    )
}

/// The full license output (version banner + GPL notice).
pub fn license() -> String {
    format!("{}\n{LICENSE_TEXT}", version())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_banner_shape() {
        // The banner tracks the workspace version, so assert everything around
        // the version number rather than the number itself.
        let banner = version();
        assert!(banner.starts_with("nessemble v"));
        assert!(banner.ends_with("\n\nCopyright 2017-2026 Kevin Selwyn\n"));
    }

    #[test]
    fn license_starts_with_version_and_has_gpl() {
        let text = license();
        assert!(text.starts_with(&version()));
        assert!(text.contains("GNU General Public License"));
    }
}
