//! Generates the 256-entry 6502 opcode table from `data/opcodes.csv`.
//!
//! The CSV is the single source of truth (imported from the upstream reference
//! project's `src/static/opcodes.csv`). Each row is:
//!
//! ```text
//! "MNEMONIC",MODE_MACRO,0xNN,length,timing,meta
//! ```
//!
//! We emit a `static OPCODES: [Opcode; 256]` indexed by opcode value.

use std::env;
use std::fs;
use std::path::Path;

fn mode_variant(macro_name: &str) -> &'static str {
    match macro_name.trim() {
        "MODE_IMPLIED" => "AddressingMode::Implied",
        "MODE_ACCUMULATOR" => "AddressingMode::Accumulator",
        "MODE_RELATIVE" => "AddressingMode::Relative",
        "MODE_IMMEDIATE" => "AddressingMode::Immediate",
        "MODE_ZEROPAGE" => "AddressingMode::ZeroPage",
        "MODE_ZEROPAGE_X" => "AddressingMode::ZeroPageX",
        "MODE_ZEROPAGE_Y" => "AddressingMode::ZeroPageY",
        "MODE_ABSOLUTE" => "AddressingMode::Absolute",
        "MODE_ABSOLUTE_Y" => "AddressingMode::AbsoluteY",
        "MODE_ABSOLUTE_X" => "AddressingMode::AbsoluteX",
        "MODE_INDIRECT" => "AddressingMode::Indirect",
        "MODE_INDIRECT_X" => "AddressingMode::IndirectX",
        "MODE_INDIRECT_Y" => "AddressingMode::IndirectY",
        other => panic!("unknown addressing mode macro in opcodes.csv: {other:?}"),
    }
}

fn parse_int(field: &str) -> u32 {
    let field = field.trim();
    if let Some(hex) = field
        .strip_prefix("0x")
        .or_else(|| field.strip_prefix("0X"))
    {
        u32::from_str_radix(hex, 16).unwrap_or_else(|_| panic!("bad hex field: {field:?}"))
    } else {
        field
            .parse()
            .unwrap_or_else(|_| panic!("bad integer field: {field:?}"))
    }
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let csv_path = Path::new(&manifest_dir).join("data/opcodes.csv");
    println!("cargo:rerun-if-changed={}", csv_path.display());

    let csv = fs::read_to_string(&csv_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", csv_path.display()));

    let mut rows: Vec<String> = Vec::with_capacity(256);
    for (lineno, line) in csv.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let fields: Vec<&str> = line.split(',').collect();
        assert!(
            fields.len() == 6,
            "opcodes.csv line {} has {} fields, expected 6: {line:?}",
            lineno + 1,
            fields.len()
        );

        let mnemonic = fields[0].trim().trim_matches('"');
        let mode = mode_variant(fields[1]);
        let opcode = parse_int(fields[2]);
        let length = parse_int(fields[3]);
        let timing = parse_int(fields[4]);
        let meta = parse_int(fields[5]);

        assert!(opcode < 256, "opcode out of range: {opcode}");
        assert!(
            opcode as usize == rows.len(),
            "opcodes.csv must be ordered by opcode value; row {} declares opcode {:#04x} but expected {:#04x}",
            lineno + 1,
            opcode,
            rows.len()
        );

        rows.push(format!(
            "    Opcode {{ mnemonic: {mnemonic:?}, mode: {mode}, opcode: {opcode:#04x}, length: {length}, timing: {timing}, meta: {meta:#04x} }},"
        ));
    }

    assert!(
        rows.len() == 256,
        "expected exactly 256 opcode rows, got {}",
        rows.len()
    );

    let generated = format!(
        "// @generated by build.rs from data/opcodes.csv — do not edit.\n\
         /// The full 256-entry 6502 opcode table, indexed by opcode byte.\n\
         pub static OPCODES: [Opcode; 256] = [\n{}\n];\n",
        rows.join("\n")
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = Path::new(&out_dir).join("opcodes_gen.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("cannot write {}: {e}", out_path.display()));
}
